name: first workflow
on:
  push:
    jobs:
      steps:
        - name: first
         run: echo"welcome to github actions"

        - name: second
         run: echo"this is my first workflow"

        - name: third
         run: echo"learning ci with github actions"
